// local
@url=https://localhost:5000

###

GET https://localhost:5001/healthz

###

GET {{url}}/switch/other:prod

### 

GET {{url}}/switch/test
environment: production

### 

POST https://localhost:5001/switch/lookup
environment: production
Content-Type: application/json

["test", "noris-rate", "noris-title"]

### 

GET {{url}}/switch/t550


###

GET {{url}}/switch/noris-rate

###

GET https://localhost:44438/switch


###

GET https://localhost:5443/switch

###

POST https://localhost:5443/switch
Content-Type: application/x-www-form-urlencoded

name=testing
&value=false

###

POST https://localhost:5443/switch
Content-Type: application/x-www-form-urlencoded

name=testing
&value=false

###

POST https://localhost:5443/switch
Content-Type: application/x-www-form-urlencoded

name=testing
&value=false