GET https://localhost:5000/switch/other:prod

### 

GET https://localhost:5000/switch/test
environment: production

### 

GET https://localhost:5000/switch/t550


###

GET https://localhost:5000/switch/noris-rate

###

GET https://localhost:44438/switch


###

GET https://localhost:5443/switch

###

POST https://localhost:5443/switch
Content-Type: application/x-www-form-urlencoded

name=testing
&value=false

###

POST https://localhost:5443/switch
Content-Type: application/x-www-form-urlencoded

name=testing
&value=false

